services:
  redis:
    image: redis:alpine
    container_name: deck-redis
    ports:
      - '16379:6379'
    networks:
      - deck

  db:
    image: postgres:18
    container_name: deck-db
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=deck
    networks:
      - deck

networks:
  deck:
    driver: bridge
