[project]
name = "server-py"
version = "0.1.0"
description = "Python high-performance service for deck"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "core-py",
]

[tool.uv.sources]
core-py = { workspace = true }
